version: '3'


x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnamic/spark/jobs
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
  networks:
    - unstructuredData

services:

  spark-master: 
    image: bitnami/spark:latest
    volumes:
      - ./jobs:/opt/bitnamic/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      # external:internal ip
      #7077 were we are submitting the jobs to
      - "9090:8080"
      - "7077:7077"

    networks:
      - unstructuredData

  #   <<: *spark-common: This line indicates that the spark-worker-1 service inherits common settings defined elsewhere in the file under an anchor labeled *spark-common. 
  #  This could include shared configuration like the image, network, and other settings for Spark worker nodes.
  spark-worker-1:
    <<: *spark-common
  spark-worker-2:
    <<: *spark-common
  spark-worker-3:
    <<: *spark-common
  spark-worker-4:
    <<: *spark-common

networks:
  unstructuredData:
